# Generated by Django 4.2.5 on 2024-03-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_customuser_name_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='verification_code',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='password', max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='username', max_length=200, unique=True),
        ),
    ]
